name: Update SKanetrafiken Warnings
on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  update_data:
    name: Update data with new warnings
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'
          cache: 'pip'
      - name: Install Dependencies
        run: pip install -r requirements.txt
      - name: Run Script and Update Plot
        run: |
          python scraper.py
      - name: Commit and Push Changes
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add disruptions.csv
          git commit -m "Updated data with GitHub Actions"
          git push origin master
